#!/usr/bin/env bash

## Initialize stack and site (full reset)
##
## Usage: fin init

# Abort if anything fails
set -e

#-------------------------- Configure --------------------------------
source $(dirname ${BASH_SOURCE})/_base.sh
cd "$PROJECT_ROOT"

#-------------------------- Execution --------------------------------
_confirm "\033[0;41mDo You really want to recreate all project components again (Docker containers, networks and volumes)?\033[0m"
