#!/usr/bin/env bash

## Share uploaded files
##
## Usage: fin share-wp-uploads

# Abort if anything fails
set -e

#-------------------------- Configure --------------------------------
source $(dirname ${BASH_SOURCE})/_base.sh
cd "$PROJECT_ROOT"

#-------------------------- Execution --------------------------------
cd "$wp_uploads_dump_dir_path" || exit 11
wp_uploads_dump_file_name=$1
if [[ -z "$wp_uploads_dump_file_name" ]]; then
    wp_uploads_dump_file_name=$(
        ls -t $wp_uploads_dump_file_pattern | head -1
    )
fi
if [[ -f "$wp_uploads_dump_file_name" ]]; then
    unzip $wp_uploads_dump_dir_path/$wp_uploads_dump_file_name -d $wp_uploads_dir_path
else
    printf "${COLOR_RED}There is no dump file under ${COLOR_RED_BG}%s${COLOR_RED} directory!${COLOR_OFF}\n" "$wp_uploads_dump_dir_path"
    printf "${COLOR_RED}Please run ${COLOR_RED_BG}%s${COLOR_RED} command to pack uploads to archive file.${COLOR_OFF}\n" "fin backup-wp-uploads"
    exit 33
fi
