#!/usr/bin/env bash

#: exec_target = cli

## Execute yarn command
##
## Usage: fin yarn

# Abort if anything fails
set -e

# fix profile
source ~/.profile

#-------------------------- Execution --------------------------------
cd "${PROJECT_ROOT}"
yarn ${@}
#-------------------------- END: Execution --------------------------------
