#!/usr/bin/env bash

#: exec_target = cli

## Execute Symfony2 console
##
## Usage: fin console

# Abort if anything fails
set -e

# fix profile
source ~/.profile

#-------------------------- Execution --------------------------------
cd "$PROJECT_ROOT"
php app/console ${@}
#-------------------------- END: Execution --------------------------------
