#!/usr/bin/env bash

## Get drupal admin URL
##
## Usage: fin dru-admin

# Abort if anything fails
# Abort if anything fails
set -e

#-------------------------- Configure --------------------------------
source $(dirname ${BASH_SOURCE})/_base.sh
cd "$PROJECT_ROOT"

#-------------------------- Execution --------------------------------
fin drush @self.docksal uli
