#!/usr/bin/env bash

#: exec_target = cli

## Drush command
##
## Usage: fin drush

# Abort if anything fails
set -e

#-------------------------- Configure --------------------------------
cd "$PROJECT_ROOT"

#-------------------------- Execution --------------------------------
php vendor/bin/drush $@
